In [1]:
import pandas as pd
import numpy as np
import os

In [14]:
print(f'Current: {os.getcwd()}')

Current: /Users/camsmithers/Desktop/Camalytics/CamalyticsEnv/Projects/Sports/NFL/Data/Datasets/basicleaning

In [13]:
os.chdir('/Users/camsmithers/Desktop/Camalytics/CamalyticsEnv/Projects/Sports/NFL/Data/Datasets/basicleaning')

In [21]:
team_stats = pd.read_csv('team_stats.csv')

In [23]:
team_stats = team_stats.drop(columns='Unnamed: 0')

In [32]:
avg_rush_attempts = team_stats.groupby(['team_name','year'])['RushAttempts'].mean().round(1).reset_index()

In [33]:
avg_rush_attempts

    team_name  year  RushAttempts
0         ARI  2021          29.1
1         ARI  2022          25.8
2         ARI  2023          26.7
3         ARI  2024          27.9
4         ARI  2025          27.0
..        ...   ...           ...
155       WAS  2021          27.9
156       WAS  2022          30.5
157       WAS  2023          23.3
158       WAS  2024          30.9
159       WAS  2025          29.5

[160 rows x 3 columns]

In [24]:
team_stats

,First_Downs,Net_Pass_Yards,Total_Yards,Turnovers,team_name,Attempts,Yards,Touchdowns,Interceptions,Fumbles,...,CompletionPct,PctYardsPass,PctYardsRush,SuccessRate4thDown,SuccessRate3rdDown,PossessionTime,DayofWeek,month,year,gamedate
0,19,283,389,3,GNB,43,291,1,3,2,...,53.5,74.8,27.2,20.0,34.8,2082,Sunday,11,2022,2022-11-06
1,19,137,254,1,DET,26,137,2,1,0,...,53.8,53.9,46.1,0.0,35.3,1518,Sunday,11,2022,2022-11-06
2,20,127,338,2,PHI,28,154,1,1,2,...,53.6,45.6,62.4,50.0,15.8,2178,Sunday,12,2024,2024-12-22
3,23,255,368,5,WAS,39,258,5,2,3,...,61.5,70.1,30.7,40.0,35.0,1422,Sunday,12,2024,2024-12-22
4,23,204,311,0,DAL,41,204,2,0,0,...,65.9,65.6,34.4,NaN,30.4,1881,Sunday,11,2023,2023-11-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2273,16,119,193,1,PIT,31,148,1,0,2,...,54.8,76.7,38.3,0.0,25.0,1320,Saturday,1,2025,2025-01-04
2274,19,242,339,1,DAL,32,253,2,0,1,...,62.5,74.6,28.6,50.0,25.0,1862,Sunday,12,2023,2023-12-24
2275,22,284,375,0,MIA,37,293,1,0,1,...,64.9,78.1,24.3,0.0,31.6,1738,Sunday,12,2023,2023-12-24
2276,18,171,264,1,WAS,32,191,1,1,1,...,68.8,72.3,35.2,33.3,20.0,1616,Thursday,11,2024,2024-11-14
2277,23,206,434,0,PHI,28,221,0,0,1,...,64.3,50.9,52.5,NaN,36.0,1984,Thursday,11,2024,2024-11-14