# Data Cleaning

## Basic Cleaning
Here I'm just cleaning up the data to be better formatted to work with. This is more focused on separating columns with multiple values into multiple columns not just a single one, renaming columns where I feel necessary, dropping some columns, fixing the date time format, and anything else I deem necessary.

### Needed Libraries

In [11]:
import pandas as pd
import numpy as np
import os

### Global Variable

In [12]:
month_choices = [9, 10, 11, 12, 1, 2]

Chaning the working directory so I don't have to hard code long path names

In [13]:
print(f'Current: {os.getcwd()}')
os.chdir('/Users/camsmithers/Desktop/Camalytics/CamalyticsEnv/Projects/Sports/NFL/Data/Datasets/htmlparse')
print(f'Current: {os.getcwd()}')

Current: /Users/camsmithers/Desktop/Camalytics/CamalyticsEnv/Projects/Sports/NFL/Data/Datasets/htmlparse
Current: /Users/camsmithers/Desktop/Camalytics/CamalyticsEnv/Projects/Sports/NFL/Data/Datasets/htmlparse

### Team Statistics

In [14]:
team_stats = pd.read_csv('team_stats.csv')

team_stats = team_stats.drop(columns='Unnamed: 0')
team_stats = team_stats.rename(columns={'Cmp-Att-Yd-TD-INT':'ManyStats'})
team_stats[['Completion', 'Attempts', 'Yards', 'Touchdowns', 'Interceptions']] = team_stats.ManyStats.str.split('-', expand=True)
team_stats = team_stats.drop(columns='ManyStats')

team_stats.columns = team_stats.columns.str.replace(' ', '_')
team_stats.columns = team_stats.columns.str.replace('.', '_')
team_stats.columns = team_stats.columns.str.replace('-', '_')

team_stats[['Success4thDown', 'Failed4thDown']] = team_stats.Fourth_Down_Conv_.str.split('-', expand=True)
team_stats[['Fumbles', 'FumblesLost']] = team_stats.Fumbles_Lost.str.split('-', expand=True)
team_stats[['Penalties', 'PenaltyYards']] = team_stats.Penalties_Yards.str.split('-', expand=True)
#team_stats[['RushAttempts', 'RushYards', 'RushTDs']] = team_stats.Rush_Yds_TDs.str.split('-', expand=True)
team_stats[['Sacked', 'SackYards']] = team_stats.Sacked_Yards.str.split('-', expand=True)
team_stats[['Success3rdDown', 'Failed3rdDown']] = team_stats.Third_Down_Conv_.str.split('-', expand=True)
team_stats[['TimeMinutes', 'TimeSeconds']] = team_stats.Time_of_Possession.str.split(':', expand=True)

team_stats = team_stats.drop(columns={'Fourth_Down_Conv_', 'Fumbles_Lost', 'Penalties_Yards', 'Sacked_Yards', 'Third_Down_Conv_', 'Time_of_Possession'})

team_stats['Rush_Yds_TDs'].str.count('-').value_counts()

team_stats.loc[2083]

team_stats.at[2083,'Rush_Yds_TDs'] = '8-neg1-0'

team_stats[['RushAttempts', 'RushYards', 'RushTDs']] = team_stats.Rush_Yds_TDs.str.split('-', expand=True)
team_stats = team_stats.drop(columns='Rush_Yds_TDs')

team_stats.at[2083, "RushYards"] = -1

skip_cols = ['team_name', 'date']
cols_to_change = [col for col in team_stats.columns if col not in skip_cols]
team_stats[cols_to_change] = team_stats[cols_to_change].astype(int)

team_stats['CompletionPct'] = round(100 * (team_stats['Completion'] / team_stats['Attempts']), 1)
team_stats['PctYardsPass'] = round(100 * (team_stats['Yards'] / team_stats['Total_Yards']), 1)
team_stats['PctYardsRush'] = round(100 * (team_stats['RushYards'] / team_stats['Total_Yards']), 1)
team_stats['SuccessRate4thDown'] = round(
    100 * (team_stats['Success4thDown'] / (team_stats['Success4thDown'] + team_stats['Failed4thDown'])), 1)
team_stats['SuccessRate3rdDown'] = round(
    100 * (team_stats['Success3rdDown'] / (team_stats['Success3rdDown'] + team_stats['Failed3rdDown'])), 1)
team_stats['PossessionTime'] = (60 * team_stats['TimeMinutes']) + team_stats['TimeSeconds']

team_stats[['DayofWeek', 'Month', 'DayofMonth', 'Year']] = team_stats.date.str.split(' ', expand=True)
team_stats['DayofMonth'] = team_stats['DayofMonth'].str.rstrip(',')

game_months = [
    (team_stats['Month'] == 'Sep'),
    (team_stats['Month'] == 'Oct'),
    (team_stats['Month'] == 'Nov'),
    (team_stats['Month'] == 'Dec'),
    (team_stats['Month'] == 'Jan'),
    (team_stats['Month'] == 'Feb')
]
month_choices = [9, 10, 11, 12, 1, 2]

team_stats['Month'] = np.select(game_months, month_choices, default=False)
team_stats['DayofMonth'] = team_stats['DayofMonth'].astype(int)
team_stats['Year'] = team_stats['Year'].astype(int)

date_mapping = {
    'Year':'year',
    'DayofMonth':'day',
    'Month':'month'}

team_stats = team_stats.rename(mapper=date_mapping, axis=1)
team_stats['gamedate'] = pd.to_datetime(team_stats[['year', 'month', 'day']])

team_stats.loc[(team_stats['gamedate'] >= '2024-08') & (team_stats['gamedate'] <= '2025-03'), 'season'] = 2024
team_stats.loc[(team_stats['gamedate'] >= '2023-08') & (team_stats['gamedate'] <= '2024-03'), 'season'] = 2023
team_stats.loc[(team_stats['gamedate'] >= '2022-08') & (team_stats['gamedate'] <= '2023-03'), 'season'] = 2022
team_stats.loc[(team_stats['gamedate'] >= '2021-08') & (team_stats['gamedate'] <= '2022-03'), 'season'] = 2021

team_stats['season'] = team_stats['season'].astype(int)

team_stats = team_stats.drop(columns={'date','Completion','Success4thDown','Failed4thDown','Success3rdDown','Failed3rdDown', 'day'})

In [15]:
team_stats.head()

,First_Downs,Net_Pass_Yards,Total_Yards,Turnovers,team_name,score,opp_score,Attempts,Yards,Touchdowns,...,PctYardsPass,PctYardsRush,SuccessRate4thDown,SuccessRate3rdDown,PossessionTime,DayofWeek,month,year,gamedate,season
0,19,283,389,3,GNB,9,15,43,291,1,...,74.8,27.2,20.0,34.8,2082,Sunday,11,2022,2022-11-06,2022
1,19,137,254,1,DET,15,9,26,137,2,...,53.9,46.1,0.0,35.3,1518,Sunday,11,2022,2022-11-06,2022
2,20,127,338,2,PHI,33,36,28,154,1,...,45.6,62.4,50.0,15.8,2178,Sunday,12,2024,2024-12-22,2024
3,23,255,368,5,WAS,36,33,39,258,5,...,70.1,30.7,40.0,35.0,1422,Sunday,12,2024,2024-12-22,2024
4,23,204,311,0,DAL,33,10,41,204,2,...,65.6,34.4,NaN,30.4,1881,Sunday,11,2023,2023-11-19,2023

### Offensive Player Statistics

In [29]:
player_offense = pd.read_csv('player_offense.csv')

new_offense_cols = ['randnumber','playername','team','completions','passattempts',
                    'passingyards','passingtds','interceptions','sackstaken','yardslostbysack',
                    'longestcompletion','passrating','rushingattempts','rushyards','rushtds',
                    'longestrush','targets','receptions','receivingyards','receivingtds',
                    'longestreception','fumbles','fumbleslost','gamedate']

player_offense.columns = new_offense_cols

realplayer = player_offense['playername'] != "Player"
playerhere = player_offense['playername'].notna()
player_offense = player_offense[realplayer]
player_offense = player_offense[playerhere]

player_offense[['dayofweek','month','day','year']] = player_offense.gamedate.str.split(' ', expand=True)
player_offense = player_offense.drop(columns='gamedate')
player_offense['day'] = player_offense['day'].str.rstrip(',')

game_months = [
    (player_offense['month'] == 'Sep'),
    (player_offense['month'] == 'Oct'),
    (player_offense['month'] == 'Nov'),
    (player_offense['month'] == 'Dec'),
    (player_offense['month'] == 'Jan'),
    (player_offense['month'] == 'Feb')
]

player_offense['month'] = np.select(game_months, month_choices, default=False)
player_offense['gamedate'] = pd.to_datetime(player_offense[['year','month','day']])

skip_cols = ['playername','team','dayofweek','gamedate']
cols_to_change = [col for col in player_offense.columns if col not in skip_cols]
player_offense[cols_to_change] = player_offense[cols_to_change].astype(float)

player_offense['completionpct'] = round(100 * (player_offense['completions'] / player_offense['passattempts']), 1)
player_offense['td2int'] = round(player_offense['passingtds'] / player_offense['interceptions'], 3)
player_offense['yardsperrush'] = round(player_offense['rushyards'] / player_offense['rushingattempts'], 1)

player_offense.loc[(player_offense['gamedate'] >= '2024-08') & (player_offense['gamedate'] <= '2025-03'), 'season'] = 2024
player_offense.loc[(player_offense['gamedate'] >= '2023-08') & (player_offense['gamedate'] <= '2024-03'), 'season'] = 2023
player_offense.loc[(player_offense['gamedate'] >= '2022-08') & (player_offense['gamedate'] <= '2023-03'), 'season'] = 2022
player_offense.loc[(player_offense['gamedate'] >= '2021-08') & (player_offense['gamedate'] <= '2022-03'), 'season'] = 2021

player_offense['season'] = player_offense['season'].astype(int)

player_offense = player_offense.drop(columns={'randnumber','day','month','year'})

/var/folders/xv/_79n8tfd6mx4j2z8m6rstygr0000gn/T/ipykernel_25530/990513246.py:14: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  player_offense = player_offense[playerhere]

In [30]:
qbs = player_offense[player_offense['passattempts'] >= 10]
rbs = player_offense[(player_offense['rushingattempts'] >= 10) & (player_offense['passattempts'] <= 2)]
wrs = player_offense[player_offense['targets'] >= 2]

### Defensive Player Statistics

In [31]:
player_defense = pd.read_csv('player_defense.csv')

new_defense_cols = ['randnum','playername','team','interceptions','intrtnyards','int2td','intlongestyards',
                    'passdeflections','sacks','soloassisttackles','solotackles','assisttackles','tackelsforloss',
                    'qbhits','fumblerecovery','fumblereturnyards','fumble2td','forcedfumble','gamedate']
player_defense.columns = new_defense_cols

player_defense = player_defense[(player_defense['playername'] != 'Player') & player_defense['playername'].notna()]

player_defense[['dayofweek','month','day','year']] = player_defense.gamedate.str.split(' ', expand=True)
player_defense = player_defense.drop(columns='gamedate')
player_defense['day'] = player_defense['day'].str.rstrip(',')

game_months = [
    (player_defense['month'] == 'Sep'),
    (player_defense['month'] == 'Oct'),
    (player_defense['month'] == 'Nov'),
    (player_defense['month'] == 'Dec'),
    (player_defense['month'] == 'Jan'),
    (player_defense['month'] == 'Feb')
]

player_defense['month'] = np.select(game_months, month_choices, default=False)
player_defense['gamedate'] = pd.to_datetime(player_defense[['year','month','day']])

skip_cols = ['playername','team','dayofweek','gamedate']
cols_to_change = [col for col in player_defense.columns if col not in skip_cols]
player_defense[cols_to_change] = player_defense[cols_to_change].astype(float)

player_defense.loc[(player_defense['gamedate'] >= '2024-08') & (player_defense['gamedate'] <= '2025-03'), 'season'] = 2024
player_defense.loc[(player_defense['gamedate'] >= '2023-08') & (player_defense['gamedate'] <= '2024-03'), 'season'] = 2023
player_defense.loc[(player_defense['gamedate'] >= '2022-08') & (player_defense['gamedate'] <= '2023-03'), 'season'] = 2022
player_defense.loc[(player_defense['gamedate'] >= '2021-08') & (player_defense['gamedate'] <= '2022-03'), 'season'] = 2021

player_defense['season'] = player_defense['season'].astype(int)

player_defense = player_defense.drop(columns={'randnum','day','month','year'})

### Advanced Passing Statistics

In [32]:
advanced_passing = pd.read_csv('passing_advanced.csv')
advanced_passing = advanced_passing.drop(columns={'Unnamed: 0','Cmp','1D'})
new_advpass_cols = ['playername','team','attempts','passingyards','firstdownsperpassplay',
                    'intendairyards','intendairyardsperpassatt','completedairyards',
                    'completedairyardspercomp','completedairyardsperpassatt',
                    'yardsaftercatch','yacpercompletion','drops','percentdrops',
                    'badthrows','badthrowspercent','sackstaken','timesblitzed',
                    'timeshurried','hitstaken','timespressured','percentdbspressured',
                    'scrambles','yardsperscramble','date']

advanced_passing.columns = new_advpass_cols

advanced_passing = advanced_passing[advanced_passing['playername'] != 'Player']

advanced_passing['percentdbspressured'] = advanced_passing['percentdbspressured'].str.rstrip('%')
advanced_passing['badthrowspercent'] = advanced_passing['badthrowspercent'].str.rstrip('%')
advanced_passing['percentdrops'] = advanced_passing['percentdrops'].str.rstrip('%')

advanced_passing[['dayofweek','month','day','year']] = advanced_passing.date.str.split(' ', expand=True)
advanced_passing = advanced_passing.drop(columns='date')
advanced_passing['day'] = advanced_passing['day'].str.rstrip(',')

game_months = [
    (advanced_passing['month'] == 'Sep'),
    (advanced_passing['month'] == 'Oct'),
    (advanced_passing['month'] == 'Nov'),
    (advanced_passing['month'] == 'Dec'),
    (advanced_passing['month'] == 'Jan'),
    (advanced_passing['month'] == 'Feb')
]

advanced_passing['month'] = np.select(game_months, month_choices, default=False)
advanced_passing['gamedate'] = pd.to_datetime(advanced_passing[['year','month','day']])

skip_cols = ['playername','team','dayofweek','gamedate']
cols_to_change = [col for col in advanced_passing.columns if col not in skip_cols]
advanced_passing[cols_to_change] = advanced_passing[cols_to_change].astype(float)

advanced_passing.loc[(advanced_passing['gamedate'] >= '2024-08') & (advanced_passing['gamedate'] <= '2025-03'), 'season'] = 2024
advanced_passing.loc[(advanced_passing['gamedate'] >= '2023-08') & (advanced_passing['gamedate'] <= '2024-03'), 'season'] = 2023
advanced_passing.loc[(advanced_passing['gamedate'] >= '2022-08') & (advanced_passing['gamedate'] <= '2023-03'), 'season'] = 2022
advanced_passing.loc[(advanced_passing['gamedate'] >= '2021-08') & (advanced_passing['gamedate'] <= '2022-03'), 'season'] = 2021

advanced_passing['season'] = advanced_passing['season'].astype(int)

advanced_passing = advanced_passing.drop(columns={'day','month','year'})

### Advanced Receiving Statistics

In [33]:
advanced_receiving = pd.read_csv('receiving_advanced.csv')
advanced_receiving = advanced_receiving.drop(columns={'Unnamed: 0','Rec/Br'})
new_advrec_cols = ['playername','team','targets','receptions','yards','touchdowns',
                   'firstdownsreceiving','yardsbeforecatch','yardsbeforecatchper',
                   'yardsaftercatch','yardsaftercatchper','avgdeptoftarget',
                   'brokentackles','drops','droprate','intsontargets',
                   'passrtgontargets','date']

advanced_receiving.columns = new_advrec_cols

advanced_receiving = advanced_receiving[advanced_receiving['playername'] != 'Player']

advanced_receiving[['dayofweek','month','day','year']] = advanced_receiving.date.str.split(' ', expand=True)
advanced_receiving = advanced_receiving.drop(columns='date')
advanced_receiving['day'] = advanced_receiving['day'].str.rstrip(',')

game_months = [
    (advanced_receiving['month'] == 'Sep'),
    (advanced_receiving['month'] == 'Oct'),
    (advanced_receiving['month'] == 'Nov'),
    (advanced_receiving['month'] == 'Dec'),
    (advanced_receiving['month'] == 'Jan'),
    (advanced_receiving['month'] == 'Feb')
]

advanced_receiving['month'] = np.select(game_months, month_choices, default=False)
advanced_receiving['gamedate'] = pd.to_datetime(advanced_receiving[['year','month','day']])

skip_cols = ['playername','team','dayofweek','gamedate']
cols_to_change = [col for col in advanced_receiving.columns if col not in skip_cols]
advanced_receiving[cols_to_change] = advanced_receiving[cols_to_change].astype(float)

advanced_receiving.loc[(advanced_receiving['gamedate'] >= '2024-08') & (advanced_receiving['gamedate'] <= '2025-03'), 'season'] = 2024
advanced_receiving.loc[(advanced_receiving['gamedate'] >= '2023-08') & (advanced_receiving['gamedate'] <= '2024-03'), 'season'] = 2023
advanced_receiving.loc[(advanced_receiving['gamedate'] >= '2022-08') & (advanced_receiving['gamedate'] <= '2023-03'), 'season'] = 2022
advanced_receiving.loc[(advanced_receiving['gamedate'] >= '2021-08') & (advanced_receiving['gamedate'] <= '2022-03'), 'season'] = 2021

advanced_receiving['season'] = advanced_receiving['season'].astype(int)

advanced_receiving = advanced_receiving.drop(columns={'day','month','year'})

### Advanced Rushing

In [34]:
advanced_rushing = pd.read_csv('rushing_advanced.csv')
advanced_rushing = advanced_rushing.drop(columns={'Unnamed: 0'})
new_advrush_cols = ['playername','team','rushes','attempts','touchdowns','firstdownsrushing',
                    'yardsbeforecontact','yardsbeforecontactper','yardsaftercontact',
                    'yardsaftercontactper','brokentackles','brokentacklesper','date']

advanced_rushing.columns = new_advrush_cols

advanced_rushing = advanced_rushing[advanced_rushing['playername'] != 'Player']

advanced_rushing[['dayofweek','month','day','year']] = advanced_rushing.date.str.split(' ', expand=True)
advanced_rushing = advanced_rushing.drop(columns='date')
advanced_rushing['day'] = advanced_rushing['day'].str.rstrip(',')

game_months = [
    (advanced_rushing['month'] == 'Sep'),
    (advanced_rushing['month'] == 'Oct'),
    (advanced_rushing['month'] == 'Nov'),
    (advanced_rushing['month'] == 'Dec'),
    (advanced_rushing['month'] == 'Jan'),
    (advanced_rushing['month'] == 'Feb')
]

advanced_rushing['month'] = np.select(game_months, month_choices, default=False)
advanced_rushing['gamedate'] = pd.to_datetime(advanced_rushing[['year','month','day']])

skip_cols = ['playername','team','dayofweek','gamedate']
cols_to_change = [col for col in advanced_rushing.columns if col not in skip_cols]
advanced_rushing[cols_to_change] = advanced_rushing[cols_to_change].astype(float)

advanced_rushing.loc[(advanced_rushing['gamedate'] >= '2024-08') & (advanced_rushing['gamedate'] <= '2025-03'), 'season'] = 2024
advanced_rushing.loc[(advanced_rushing['gamedate'] >= '2023-08') & (advanced_rushing['gamedate'] <= '2024-03'), 'season'] = 2023
advanced_rushing.loc[(advanced_rushing['gamedate'] >= '2022-08') & (advanced_rushing['gamedate'] <= '2023-03'), 'season'] = 2022
advanced_rushing.loc[(advanced_rushing['gamedate'] >= '2021-08') & (advanced_rushing['gamedate'] <= '2022-03'), 'season'] = 2021

advanced_rushing['season'] = advanced_rushing['season'].astype(int)

advanced_rushing = advanced_rushing.drop(columns={'day','month','year'})

### Advanced Defensive Statistics

In [35]:
advanced_defense = pd.read_csv('defense_advanced.csv')
new_advdef_cols = ['randnum','playername','team','interceptions','deftargets','completions',
                   'cmppctincoverage','yardsallowed','yardsallowedpercmp',
                   'yardspertarget','tdsallowed','passrtgallowed',
                   'agvdepthoftargetcvg','airyardsoncmps','yardsaftercatch',
                   'blitzes','qbhurries','qbknockdown','sacks','pressures',
                   'soloassisttackles','missedtackles','missedtacklepct','date']
advanced_defense.columns = new_advdef_cols

advanced_defense = advanced_defense.drop(columns={'randnum', 'completions','airyardsoncmps'})

advanced_defense = advanced_defense[advanced_defense['playername'] != 'Player']

advanced_defense['cmppctincoverage'] = advanced_defense['cmppctincoverage'].str.rstrip('%')
advanced_defense['missedtacklepct'] = advanced_defense['missedtacklepct'].str.rstrip('%')

advanced_defense[['dayofweek','month','day','year']] = advanced_defense.date.str.split(' ', expand=True)
advanced_defense = advanced_defense.drop(columns='date')
advanced_defense['day'] = advanced_defense['day'].str.rstrip(',')

game_months = [
    (advanced_defense['month'] == 'Sep'),
    (advanced_defense['month'] == 'Oct'),
    (advanced_defense['month'] == 'Nov'),
    (advanced_defense['month'] == 'Dec'),
    (advanced_defense['month'] == 'Jan'),
    (advanced_defense['month'] == 'Feb')
]

advanced_defense['month'] = np.select(game_months, month_choices, default=False)
advanced_defense['gamedate'] = pd.to_datetime(advanced_defense[['year','month','day']])

skip_cols = ['playername','team','dayofweek','gamedate']
cols_to_change = [col for col in advanced_defense.columns if col not in skip_cols]
advanced_defense[cols_to_change] = advanced_defense[cols_to_change].astype(float)

advanced_defense.loc[(advanced_defense['gamedate'] >= '2024-08') & (advanced_defense['gamedate'] <= '2025-03'), 'season'] = 2024
advanced_defense.loc[(advanced_defense['gamedate'] >= '2023-08') & (advanced_defense['gamedate'] <= '2024-03'), 'season'] = 2023
advanced_defense.loc[(advanced_defense['gamedate'] >= '2022-08') & (advanced_defense['gamedate'] <= '2023-03'), 'season'] = 2022
advanced_defense.loc[(advanced_defense['gamedate'] >= '2021-08') & (advanced_defense['gamedate'] <= '2022-03'), 'season'] = 2021

advanced_defense['season'] = advanced_defense['season'].astype(int)

advanced_defense = advanced_defense.drop(columns={'day','month','year'})

## Export to CSV 1
Ensuring that I don't have to rerun all these chunks of code each time

In [24]:
print(f'Current: {os.getcwd()}')
os.chdir('/Users/camsmithers/Desktop/Camalytics/CamalyticsEnv/Projects/Sports/NFL/Data/Datasets/cleaned')
print(f'Current: {os.getcwd()}')

Current: /Users/camsmithers/Desktop/Camalytics/CamalyticsEnv/Projects/Sports/NFL/Data/Datasets/finished
Current: /Users/camsmithers/Desktop/Camalytics/CamalyticsEnv/Projects/Sports/NFL/Data/Datasets/cleaned

In [ ]:
#team_stats.to_csv('team_stats.csv')
#qbs.to_csv('qbs.csv')
#rbs.to_csv('rbs.csv')
#wrs.to_csv('wrs.csv')
#player_defense.to_csv('player_defense.csv')
#advanced_passing.to_csv('adv_pass.csv')
#advanced_receiving.to_csv('adv_receiving.csv')
#advanced_rushing.to_csv('adv_rush.csv')
#advanced_defense.to_csv('adv_def.csv')

## Pre-Analysis Cleaning

In [32]:
print(f'Current: {os.getcwd()}')
os.chdir('/Users/camsmithers/Desktop/Camalytics/CamalyticsEnv/Projects/Sports/NFL/Data/Datasets/cleaned')
print(f'Current: {os.getcwd()}')

Current: /Users/camsmithers/Desktop/Camalytics/CamalyticsEnv/Projects/Sports/NFL/Data/Datasets/finished
Current: /Users/camsmithers/Desktop/Camalytics/CamalyticsEnv/Projects/Sports/NFL/Data/Datasets/cleaned

### Team Stats

In [40]:
team_stats = pd.read_csv('team_stats.csv')
team_stats = team_stats.drop(columns={'Unnamed: 0','TimeMinutes','TimeSeconds'})
team_stats['Yards_Per_Penalty'] = round(team_stats['PenaltyYards'] / team_stats['Penalties'], 1)
team_stats['gameplayed'] = 1
team_stats['outcome'] = np.where(team_stats['score'] > team_stats['opp_score'], 1, 0)
team_stats['outcome2'] = np.where(team_stats['score'] > team_stats['opp_score'], 'Win', 'Loss')
team_stats['movementmethod'] = np.where(team_stats['Attempts'] > team_stats['RushAttempts'], 'Passing', 'Rushing')
team_stats['yardagemethod'] = np.where(team_stats['PctYardsPass'] > team_stats['PctYardsRush'], 'Passing', 'Rushing')


avg_stats = team_stats.groupby(
    ['team_name','season']).agg(
        {'First_Downs':'mean', 'Turnovers':'mean', 'Attempts':'mean', 'Yards':'mean',
         'Interceptions':'mean', 'RushAttempts':'mean', 'RushYards':'mean',
         'CompletionPct':'mean', 'PctYardsPass':'mean', 'PctYardsRush':'mean',
         'SuccessRate4thDown':'mean', 'SuccessRate3rdDown':'mean', 'PossessionTime':'mean',
         'Yards_Per_Penalty':'mean', 'Penalties':'mean'
            }).round(1)

avg_stats = avg_stats.add_suffix('_avg')

more_stats = team_stats.groupby(
    ['team_name', 'season']).agg(
        {'gameplayed':'sum', 'outcome':'sum'})

more_stats = more_stats.add_suffix('_total')

team_stats_b2g = pd.merge(left=team_stats, right=avg_stats, left_on=['team_name','season'],
                          right_on=['team_name','season'], how='left')
team_stats_b2g = pd.merge(left=team_stats_b2g, right=more_stats, left_on=['team_name', 'season'],
                          right_on=['team_name', 'season'], how='left')

team_stats_b2g = team_stats_b2g[['team_name'] + [col for col in team_stats_b2g.columns if col != 'team_name']]
team_stats_b2g = team_stats_b2g[['gamedate'] + [col for col in team_stats_b2g.columns if col != 'gamedate']]
team_stats_b2g = team_stats_b2g.drop(columns={'DayofWeek','month'})

team_stats_b2g.columns = team_stats_b2g.columns.str.lower()

team_stats_b2g['win_pct'] = round(100 * (team_stats_b2g['outcome_total'] / team_stats_b2g['gameplayed_total']), 1)
team_stats_b2g['possession_pct'] = round(100 * (team_stats_b2g['possessiontime'] / 3600), 1)
team_stats_b2g['possession_pct_avg'] = round(100 * (team_stats_b2g['possessiontime_avg'] / 3600), 1)
team_stats_b2g['win_possession'] = np.where(team_stats_b2g['possession_pct'] > 50.0, 'Yes', 'No')

In [41]:
team_stats_b2g

,gamedate,team_name,first_downs,net_pass_yards,total_yards,turnovers,score,opp_score,attempts,yards,...,successrate3rddown_avg,possessiontime_avg,yards_per_penalty_avg,penalties_avg,gameplayed_total,outcome_total,win_pct,possession_pct,possession_pct_avg,win_possession
0,2022-11-06,GNB,19,283,389,3,9,15,43,291,...,26.5,1914.6,8.7,5.2,17,8,47.1,57.8,53.2,Yes
1,2022-11-06,DET,19,137,254,1,15,9,26,137,...,28.6,1795.5,8.6,5.3,17,9,52.9,42.2,49.9,No
2,2024-12-22,PHI,20,127,338,2,33,36,28,154,...,27.6,1941.0,7.4,6.0,21,18,85.7,60.5,53.9,Yes
3,2024-12-22,WAS,23,255,368,5,36,33,39,258,...,30.4,1873.6,8.4,6.4,20,14,70.0,39.5,52.0,No
4,2023-11-19,DAL,23,204,311,0,33,10,41,204,...,32.7,1905.4,8.2,6.7,18,12,66.7,52.2,52.9,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2273,2025-01-04,PIT,16,119,193,1,17,19,31,148,...,28.0,1813.2,7.9,6.1,18,10,55.6,36.7,50.4,No
2274,2023-12-24,DAL,19,242,339,1,20,22,32,253,...,32.7,1905.4,8.2,6.7,18,12,66.7,51.7,52.9,Yes
2275,2023-12-24,MIA,22,284,375,0,22,20,37,293,...,27.7,1796.1,7.8,5.8,18,11,61.1,48.3,49.9,No
2276,2024-11-14,WAS,18,171,264,1,18,26,32,191,...,30.4,1873.6,8.4,6.4,20,14,70.0,44.9,52.0,No
2277,2024-11-14,PHI,23,206,434,0,26,18,28,221,...,27.6,1941.0,7.4,6.0,21,18,85.7,55.1,53.9,Yes

### Player Offense

#### QBs

In [ ]:
qbs = pd.read_csv('qbs.csv')

qbs = qbs.drop(columns={
    'Unnamed: 0','targets','receptions','receivingyards','receivingtds',
    'longestreception','dayofweek'})

###
# Changing values that initially came out as infinity with a missing value in stead
# This gets rid of the values that were dividing by zero
###
qbs['td2int'] = qbs['td2int'].replace(np.inf, np.nan)

avg_qb_stats = qbs.groupby(['playername', 'season']).agg(
    {'passattempts':'mean', 'passingyards':'mean', 'passingtds':'mean',
     'interceptions':'mean', 'sackstaken':'mean', 'yardslostbysack':'mean',
     'passrating':'mean', 'rushingattempts':'mean', 'rushtds':'mean',
     'completionpct':'mean'}).round(1)

avg_qb_stats = avg_qb_stats.add_suffix('_sn_avg')

qb_stats_b2g = pd.merge(left=qbs, right=avg_qb_stats,
                        left_on=['playername', 'season'], right_on=['playername', 'season'],
                        how='left')

qb_stats_b2g = qb_stats_b2g[['gamedate'] + [col for col in qb_stats_b2g.columns if col != 'gamedate']]

In [47]:
qb_stats_b2g

,gamedate,playername,team,completions,passattempts,passingyards,passingtds,interceptions,sackstaken,yardslostbysack,...,passattempts_sn_avg,passingyards_sn_avg,passingtds_sn_avg,interceptions_sn_avg,sackstaken_sn_avg,yardslostbysack_sn_avg,passrating_sn_avg,rushingattempts_sn_avg,rushtds_sn_avg,completionpct_sn_avg
0,2022-11-06,Aaron Rodgers,GNB,23.0,43.0,291.0,1.0,3.0,1.0,8.0,...,31.9,217.4,1.5,0.7,1.9,15.2,93.7,2.0,0.1,65.2
1,2022-11-06,Jared Goff,DET,14.0,26.0,137.0,2.0,1.0,0.0,0.0,...,34.5,261.1,1.7,0.4,1.4,9.2,98.5,1.7,0.0,65.3
2,2024-12-22,Kenny Pickett,PHI,14.0,24.0,143.0,1.0,1.0,3.0,25.0,...,19.5,143.0,1.0,0.5,1.5,12.5,95.8,3.0,0.5,62.5
3,2024-12-22,Jayden Daniels,WAS,24.0,39.0,258.0,5.0,2.0,1.0,3.0,...,31.2,230.7,1.6,0.5,2.7,13.9,98.7,9.5,0.4,68.6
4,2023-11-19,Dak Prescott,DAL,25.0,38.0,189.0,2.0,0.0,0.0,0.0,...,36.1,273.3,2.2,0.6,2.4,15.1,103.0,3.4,0.1,69.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2363,2025-01-04,Russell Wilson,PIT,17.0,31.0,148.0,1.0,0.0,4.0,29.0,...,30.4,229.3,1.5,0.4,3.1,19.8,98.5,3.8,0.2,63.8
2364,2023-12-24,Dak Prescott,DAL,20.0,32.0,253.0,2.0,0.0,4.0,11.0,...,36.1,273.3,2.2,0.6,2.4,15.1,103.0,3.4,0.1,69.1
2365,2023-12-24,Tua Tagovailoa,MIA,24.0,37.0,293.0,1.0,0.0,1.0,9.0,...,33.3,267.9,1.7,0.8,1.7,10.1,98.9,2.1,0.0,69.1
2366,2024-11-14,Jayden Daniels,WAS,22.0,32.0,191.0,1.0,1.0,3.0,20.0,...,31.2,230.7,1.6,0.5,2.7,13.9,98.7,9.5,0.4,68.6
2367,2024-11-14,Jalen Hurts,PHI,18.0,28.0,221.0,0.0,0.0,2.0,15.0,...,24.9,201.0,1.3,0.3,2.8,20.6,107.0,10.1,1.1,69.6

#### RBs

In [ ]:
rbs = pd.read_csv('rbs.csv')

rbs = rbs.drop(columns={
    'Unnamed: 0','completions','passingyards','passingtds','interceptions',
    'sackstaken','yardslostbysack','longestcompletion','passrating',
    'longestreception','dayofweek','completionpct','td2int','passattempts'})

avg_rb_stats = rbs.groupby(['playername', 'season']).agg(
    {'rushingattempts':'mean', 'rushyards':'mean', 'targets':'mean',
     'receptions':'mean', 'receivingyards':'mean', 'fumbles':'mean',
     'yardsperrush':'mean'}).round(1)

avg_rb_stats = avg_rb_stats.add_suffix('_sn_avg')

rb_stats_b2g = pd.merge(left=rbs, right=avg_rb_stats,
                        left_on=['playername', 'season'], right_on=['playername', 'season'],
                        how='left')

col_2_move = rb_stats_b2g.pop('gamedate')

rb_stats_b2g.insert(0, 'gamedate', col_2_move)

rb_stats_b2g = rb_stats_b2g[~rb_stats_b2g['playername'].isin(qb_stats_b2g['playername'])]

In [55]:
rb_stats_b2g

,gamedate,playername,team,rushingattempts,rushyards,rushtds,longestrush,targets,receptions,receivingyards,...,fumbleslost,yardsperrush,season,rushingattempts_sn_avg,rushyards_sn_avg,targets_sn_avg,receptions_sn_avg,receivingyards_sn_avg,fumbles_sn_avg,yardsperrush_sn_avg
0,2022-11-06,AJ Dillon,GNB,11.0,34.0,0.0,9.0,4.0,2.0,10.0,...,0.0,3.1,2022,12.8,50.9,2.9,2.0,14.3,0.1,4.0
1,2022-11-06,Jamaal Williams,DET,24.0,81.0,0.0,14.0,0.0,0.0,0.0,...,0.0,3.4,2022,15.9,65.9,0.9,0.6,4.4,0.2,4.1
2,2024-12-22,Saquon Barkley,PHI,29.0,150.0,2.0,68.0,1.0,0.0,0.0,...,0.0,5.2,2024,21.8,125.2,2.9,2.3,17.6,0.1,5.9
3,2024-12-22,Brian Robinson Jr.,WAS,10.0,24.0,0.0,6.0,3.0,2.0,17.0,...,2.0,2.4,2024,14.7,63.4,1.9,1.6,11.7,0.1,4.2
4,2023-11-19,Tony Pollard,DAL,12.0,61.0,1.0,22.0,5.0,4.0,19.0,...,0.0,5.1,2023,15.2,60.7,4.2,3.4,17.9,0.1,4.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2265,2025-01-04,Najee Harris,PIT,12.0,36.0,1.0,11.0,5.0,4.0,20.0,...,0.0,3.0,2024,16.5,65.8,3.1,2.3,18.4,0.0,4.0
2266,2023-12-24,Tony Pollard,DAL,12.0,38.0,0.0,7.0,1.0,1.0,5.0,...,0.0,3.2,2023,15.2,60.7,4.2,3.4,17.9,0.1,4.1
2267,2023-12-24,Raheem Mostert,MIA,11.0,46.0,0.0,15.0,1.0,1.0,4.0,...,0.0,4.2,2023,14.8,73.7,1.8,1.6,10.2,0.2,5.0
2268,2024-11-14,Brian Robinson Jr.,WAS,16.0,63.0,1.0,18.0,1.0,1.0,9.0,...,0.0,3.9,2024,14.7,63.4,1.9,1.6,11.7,0.1,4.2
2269,2024-11-14,Saquon Barkley,PHI,26.0,146.0,2.0,39.0,3.0,2.0,52.0,...,0.0,5.6,2024,21.8,125.2,2.9,2.3,17.6,0.1,5.9

#### WRs (TEs)

In [60]:
wrs = pd.read_csv('wrs.csv')

wrs = wrs.drop(columns={
    'Unnamed: 0','completions','passattempts','passingyards','interceptions','sackstaken','yardslostbysack',
    'longestcompletion','passrating','rushingattempts','rushyards','rushtds','longestrush','fumbles',
    'fumbleslost','dayofweek','completionpct','td2int','yardsperrush','passingtds'})

avg_wr_stats = wrs.groupby(['playername', 'season']).agg({
    'targets':'mean', 'longestreception':'mean',
    'receptions':'mean', 'receivingyards':'mean',
    'receivingtds':'mean'}).round(1)

avg_wr_stats = avg_wr_stats.add_suffix('_avg')

wr_stats_b2g = pd.merge(left=wrs, right=avg_wr_stats,
                        left_on=['playername', 'season'], right_on=['playername', 'season'],
                        how='left')

col_2_move = wr_stats_b2g.pop('gamedate')

wr_stats_b2g.insert(0, 'gamedate', col_2_move)

wr_stats_b2g = wr_stats_b2g[~wr_stats_b2g['playername'].isin(rb_stats_b2g['playername'])]

In [61]:
wr_stats_b2g

,gamedate,playername,team,targets,receptions,receivingyards,receivingtds,longestreception,season,targets_avg,longestreception_avg,receptions_avg,receivingyards_avg,receivingtds_avg
2,2022-11-06,Allen Lazard,GNB,10.0,4.0,87.0,1.0,47.0,2022,6.7,23.9,4.0,52.5,0.4
3,2022-11-06,Josiah Deguara,GNB,5.0,5.0,41.0,0.0,25.0,2022,3.0,17.3,3.0,29.3,0.0
4,2022-11-06,Samori Toure,GNB,4.0,2.0,34.0,0.0,32.0,2022,4.0,34.5,1.5,35.5,0.5
5,2022-11-06,Robert Tonyan,GNB,4.0,3.0,29.0,0.0,17.0,2022,4.1,15.0,3.2,28.9,0.1
6,2022-11-06,Christian Watson,GNB,2.0,2.0,24.0,0.0,18.0,2022,5.3,25.8,3.2,49.8,0.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13796,2024-11-14,Dyami Brown,WAS,2.0,1.0,4.0,0.0,4.0,2024,3.9,20.9,2.9,35.1,0.1
13798,2024-11-14,A.J. Brown,PHI,8.0,5.0,65.0,0.0,25.0,2024,7.1,28.4,4.6,73.1,0.5
13799,2024-11-14,Dallas Goedert,PHI,5.0,5.0,61.0,0.0,32.0,2024,5.5,23.4,4.5,54.7,0.2
13800,2024-11-14,DeVonta Smith,PHI,6.0,4.0,29.0,0.0,21.0,2024,6.2,25.9,4.9,60.2,0.5
13801,2024-11-14,Jahan Dotson,PHI,2.0,1.0,8.0,0.0,8.0,2024,3.8,11.5,2.1,23.6,0.1

### Advanced Offensive Metrics

#### Passing

In [62]:
adv_passing = pd.read_csv('adv_pass.csv')

adv_passing = adv_passing.drop(columns={
    'Unnamed: 0','attempts','intendairyardsperpassatt',
    'completedairyardspercomp','completedairyardsperpassatt','drops',
    'percentdrops','hitstaken','dayofweek'})

adv_passing['pctyardsyac'] = round(100 * (adv_passing['yardsaftercatch'] / adv_passing['passingyards']),1)

avg_adv_pass = adv_passing.groupby(['playername', 'season']).agg({
    'yardsaftercatch':'mean', 'badthrows':'mean', 'badthrowspercent':'mean',
    'timesblitzed':'mean', 'timespressured':'mean', 'scrambles':'mean'}).round(1)

avg_adv_pass = avg_adv_pass.add_suffix('_sn_avg')

adv_passing = adv_passing.drop(columns='passingyards')

adv_pass_stats_b2g = pd.merge(left=adv_passing, right=avg_adv_pass,
                              left_on=['playername', 'season'], right_on=['playername', 'season'],
                              how='left')

full_passing = pd.merge(left=qb_stats_b2g, right=adv_pass_stats_b2g,
                        left_on=('playername','gamedate', 'season','team','sackstaken'),
                        right_on=('playername','gamedate', 'season','team','sackstaken'),
                        how='left')

In [63]:
full_passing

,gamedate,playername,team,completions,passattempts,passingyards,passingtds,interceptions,sackstaken,yardslostbysack,...,percentdbspressured,scrambles,yardsperscramble,pctyardsyac,yardsaftercatch_sn_avg,badthrows_sn_avg,badthrowspercent_sn_avg,timesblitzed_sn_avg,timespressured_sn_avg,scrambles_sn_avg
0,2022-11-06,Aaron Rodgers,GNB,23.0,43.0,291.0,1.0,3.0,1.0,8.0,...,12.8,3.0,13.7,37.5,110.5,4.5,14.4,8.0,6.4,0.8
1,2022-11-06,Jared Goff,DET,14.0,26.0,137.0,2.0,1.0,0.0,0.0,...,15.4,0.0,NaN,67.9,134.5,5.5,16.9,10.9,7.0,0.8
2,2024-12-22,Kenny Pickett,PHI,14.0,24.0,143.0,1.0,1.0,3.0,25.0,...,26.7,3.0,4.3,21.0,11.4,1.4,54.6,4.6,2.4,0.6
3,2024-12-22,Jayden Daniels,WAS,24.0,39.0,258.0,5.0,2.0,1.0,3.0,...,8.9,5.0,9.6,44.6,110.6,4.2,14.2,9.1,6.8,4.3
4,2023-11-19,Dak Prescott,DAL,25.0,38.0,189.0,2.0,0.0,0.0,0.0,...,12.8,1.0,3.0,43.9,118.1,4.3,12.1,9.6,6.8,1.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2363,2025-01-04,Russell Wilson,PIT,17.0,31.0,148.0,1.0,0.0,4.0,29.0,...,24.3,2.0,7.5,39.2,104.0,4.6,16.8,7.9,9.6,1.9
2364,2023-12-24,Dak Prescott,DAL,20.0,32.0,253.0,2.0,0.0,4.0,11.0,...,36.8,2.0,12.0,44.3,118.1,4.3,12.1,9.6,6.8,1.9
2365,2023-12-24,Tua Tagovailoa,MIA,24.0,37.0,293.0,1.0,0.0,1.0,9.0,...,13.2,0.0,NaN,32.8,125.9,4.9,14.5,6.9,5.6,0.9
2366,2024-11-14,Jayden Daniels,WAS,22.0,32.0,191.0,1.0,1.0,3.0,20.0,...,7.7,4.0,3.8,76.4,110.6,4.2,14.2,9.1,6.8,4.3
2367,2024-11-14,Jalen Hurts,PHI,18.0,28.0,221.0,0.0,0.0,2.0,15.0,...,11.8,4.0,5.0,60.2,92.6,2.9,15.8,8.4,6.4,2.6

#### Rushing

In [64]:
adv_rushing = pd.read_csv('adv_rush.csv')

adv_rushing = adv_rushing.drop(columns={
    'Unnamed: 0','rushes','attempts','touchdowns'})

avg_adv_rush = adv_rushing.groupby(['playername', 'season']).agg({
    'yardsbeforecontact':'mean', 'yardsaftercontact':'mean'}).round(1)

avg_adv_rush = avg_adv_rush.add_suffix('_sn_avg')

adv_rush_stats_b2g = pd.merge(left=adv_rushing, right=avg_adv_rush,
                              left_on=['playername', 'season'], right_on=['playername', 'season'], how='left')

full_rushing = pd.merge(left=rb_stats_b2g, right=adv_rush_stats_b2g,
                        left_on=('gamedate','playername', 'season', 'team'),
                        right_on=('gamedate','playername', 'season', 'team'),
                        how='left')

In [65]:
full_rushing

,gamedate,playername,team,rushingattempts,rushyards,rushtds,longestrush,targets,receptions,receivingyards,...,firstdownsrushing,yardsbeforecontact,yardsbeforecontactper,yardsaftercontact,yardsaftercontactper,brokentackles,brokentacklesper,dayofweek,yardsbeforecontact_sn_avg,yardsaftercontact_sn_avg
0,2022-11-06,AJ Dillon,GNB,11.0,34.0,0.0,9.0,4.0,2.0,10.0,...,3.0,19.0,1.7,15.0,1.4,0.0,NaN,Sunday,26.6,18.6
1,2022-11-06,Jamaal Williams,DET,24.0,81.0,0.0,14.0,0.0,0.0,0.0,...,4.0,37.0,1.5,44.0,1.8,2.0,12.0,Sunday,36.8,25.9
2,2024-12-22,Saquon Barkley,PHI,29.0,150.0,2.0,68.0,1.0,0.0,0.0,...,5.0,122.0,4.2,28.0,1.0,1.0,29.0,Sunday,78.2,47.0
3,2024-12-22,Brian Robinson Jr.,WAS,10.0,24.0,0.0,6.0,3.0,2.0,17.0,...,2.0,16.0,1.6,8.0,0.8,0.0,NaN,Sunday,26.3,28.3
4,2023-11-19,Tony Pollard,DAL,12.0,61.0,1.0,22.0,5.0,4.0,19.0,...,3.0,46.0,3.8,15.0,1.3,2.0,6.0,Sunday,29.3,29.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2261,2025-01-04,Najee Harris,PIT,12.0,36.0,1.0,11.0,5.0,4.0,20.0,...,4.0,17.0,1.4,19.0,1.6,0.0,NaN,Saturday,28.4,30.5
2262,2023-12-24,Tony Pollard,DAL,12.0,38.0,0.0,7.0,1.0,1.0,5.0,...,3.0,12.0,1.0,26.0,2.2,2.0,6.0,Sunday,29.3,29.7
2263,2023-12-24,Raheem Mostert,MIA,11.0,46.0,0.0,15.0,1.0,1.0,4.0,...,3.0,18.0,1.6,28.0,2.5,1.0,11.0,Sunday,35.4,29.9
2264,2024-11-14,Brian Robinson Jr.,WAS,16.0,63.0,1.0,18.0,1.0,1.0,9.0,...,4.0,22.0,1.4,41.0,2.6,0.0,NaN,Thursday,26.3,28.3
2265,2024-11-14,Saquon Barkley,PHI,26.0,146.0,2.0,39.0,3.0,2.0,52.0,...,7.0,87.0,3.3,59.0,2.3,0.0,NaN,Thursday,78.2,47.0

#### Recieving

In [67]:
adv_receiving = pd.read_csv('adv_receiving.csv')

adv_receiving = adv_receiving.drop(columns={
    'Unnamed: 0','targets','receptions','yards','touchdowns','brokentackles',
    'intsontargets'})

avg_adv_rec = adv_receiving.groupby(['playername', 'season']).agg({
    'yardsbeforecatch':'mean', 'yardsaftercatch':'mean',
    'avgdeptoftarget':'mean', 'passrtgontargets':'mean'}).round(1)

avg_adv_rec = avg_adv_rec.add_suffix('_sn_avg')

adv_rec_stats_b2g = pd.merge(left=adv_receiving, right=avg_adv_rec,
                             left_on=['playername', 'season'],right_on=['playername', 'season'],
                             how='left')

full_receiving = pd.merge(left=wr_stats_b2g, right=adv_rec_stats_b2g,
                          left_on=('playername','team','gamedate', 'season'),
                          right_on=('playername','team','gamedate', 'season'),
                          how='left')

In [68]:
full_receiving

,gamedate,playername,team,targets,receptions,receivingyards,receivingtds,longestreception,season,targets_avg,...,yardsaftercatchper,avgdeptoftarget,drops,droprate,passrtgontargets,dayofweek,yardsbeforecatch_sn_avg,yardsaftercatch_sn_avg,avgdeptoftarget_sn_avg,passrtgontargets_sn_avg
0,2022-11-06,Allen Lazard,GNB,10.0,4.0,87.0,1.0,47.0,2022,6.7,...,7.5,15.0,0.0,0.0,65.4,Sunday,36.0,16.5,12.0,87.6
1,2022-11-06,Josiah Deguara,GNB,5.0,5.0,41.0,0.0,25.0,2022,3.0,...,2.6,5.6,0.0,0.0,100.8,Sunday,5.7,7.0,1.8,86.7
2,2022-11-06,Samori Toure,GNB,4.0,2.0,34.0,0.0,32.0,2022,4.0,...,4.0,24.3,0.0,0.0,79.2,Sunday,17.8,2.8,12.4,90.9
3,2022-11-06,Robert Tonyan,GNB,4.0,3.0,29.0,0.0,17.0,2022,4.1,...,1.0,11.3,0.0,0.0,55.2,Sunday,14.2,13.4,5.8,89.3
4,2022-11-06,Christian Watson,GNB,2.0,2.0,24.0,0.0,18.0,2022,5.3,...,4.5,7.5,0.0,0.0,116.7,Sunday,23.9,19.7,10.9,95.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10805,2024-11-14,Dyami Brown,WAS,2.0,1.0,4.0,0.0,4.0,2024,3.9,...,8.0,4.0,1.0,50.0,56.2,Thursday,12.7,17.2,6.5,98.5
10806,2024-11-14,A.J. Brown,PHI,8.0,5.0,65.0,0.0,25.0,2024,7.1,...,4.4,9.1,0.0,0.0,88.0,Thursday,49.5,23.6,13.0,107.4
10807,2024-11-14,Dallas Goedert,PHI,5.0,5.0,61.0,0.0,32.0,2024,5.5,...,5.8,6.4,0.0,0.0,117.5,Thursday,23.2,27.6,7.2,104.4
10808,2024-11-14,DeVonta Smith,PHI,6.0,4.0,29.0,0.0,21.0,2024,6.2,...,4.5,7.2,1.0,16.7,77.8,Thursday,38.8,21.4,8.6,109.8
10809,2024-11-14,Jahan Dotson,PHI,2.0,1.0,8.0,0.0,8.0,2024,3.8,...,14.0,0.5,0.0,0.0,60.4,Thursday,11.2,5.6,10.7,76.3

## Export to CSV 2

In [70]:
print(f'Current: {os.getcwd()}')
os.chdir('/Users/camsmithers/Desktop/Camalytics/CamalyticsEnv/Projects/Sports/NFL/Data/Datasets/finished')
print(f'Current: {os.getcwd()}')

Current: /Users/camsmithers/Desktop/Camalytics/CamalyticsEnv/Projects/Sports/NFL/Data/Datasets/finished
Current: /Users/camsmithers/Desktop/Camalytics/CamalyticsEnv/Projects/Sports/NFL/Data/Datasets/finished

In [ ]:
#team_stats_b2g.to_csv('full_team_stats.csv')
#full_passing.to_csv('full_passing.csv')
#full_rushing.to_csv('full_rushing.csv')
#full_receiving.to_csv('full_receiving.csv')